//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAngularApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAX_Venda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAX_Venda()
        {
            this.CAX_VendaProduto = new HashSet<CAX_VendaProduto>();
        }
    
        public int cod_Venda { get; set; }
        public System.DateTime dta_Venda { get; set; }
        public string cod_Login { get; set; }
        public Nullable<decimal> vlr_Venda { get; set; }
        public string flg_Status { get; set; }
        public Nullable<int> cod_Recebimento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAX_VendaProduto> CAX_VendaProduto { get; set; }
    }
}
