//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAngularApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAX_VendaProduto
    {
        public int cod_VendaProduto { get; set; }
        public Nullable<int> cod_Produto { get; set; }
        public Nullable<decimal> vlr_Produto { get; set; }
        public Nullable<int> qtd_Produto { get; set; }
        public string flg_Ativo { get; set; }
        public Nullable<int> cod_Venda { get; set; }
    
        public virtual CAX_Venda CAX_Venda { get; set; }
        public virtual COR_Produto COR_Produto { get; set; }
    }
}
