//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAngularApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COR_GrupoProduto
    {
        public int cod_GrupoProduto { get; set; }
        public string nom_GrupoProduto { get; set; }
        public string des_Descricao { get; set; }
        public string flg_Ativo { get; set; }
    }
}
