//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAngularApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COR_Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COR_Produto()
        {
            this.CAX_VendaProduto = new HashSet<CAX_VendaProduto>();
        }
    
        public int cod_Produto { get; set; }
        public string nom_Produto { get; set; }
        public Nullable<int> cod_GrupoProduto { get; set; }
        public Nullable<int> cod_Embalagem { get; set; }
        public Nullable<int> qtd_EstoqueMinimo { get; set; }
        public string cod_EAN { get; set; }
        public Nullable<decimal> vlr_Compra { get; set; }
        public Nullable<decimal> vlr_Venda { get; set; }
        public string des_Descricao { get; set; }
        public Nullable<int> cod_Fabricante { get; set; }
        public string flg_Ativo { get; set; }
        public Nullable<System.DateTime> dta_Cadastro { get; set; }
        public string des_Imagem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAX_VendaProduto> CAX_VendaProduto { get; set; }
    }
}
