//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAngularApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SQL_AzureEntities : DbContext
    {
        public SQL_AzureEntities()
            : base("name=SQL_AzureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAX_Venda> CAX_Venda { get; set; }
        public virtual DbSet<CAX_VendaProduto> CAX_VendaProduto { get; set; }
        public virtual DbSet<COR_Embalagem> COR_Embalagem { get; set; }
        public virtual DbSet<COR_GrupoProduto> COR_GrupoProduto { get; set; }
        public virtual DbSet<COR_Produto> COR_Produto { get; set; }
    }
}
